services:
  sge_web:
    build: .
    container_name: sge_web
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - sge_db
    env_file:
      - .env

  sge_db:
    image: postgres:15
    container_name: sge_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  sge_pgadmin:
    image: dpage/pgadmin4
    container_name: sge_pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 15432:80
    depends_on:
      - sge_db

volumes:
  postgres_data:
